export const NEXT_PAGE = 'NEXT_PAGE';
export const TOGGLE_PRODUCT_DETAIL = 'TOGGLE_PRODUCT_DETAIL';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const TOGGLE_GRID_SIZE = 'TOGGLE_GRID_SIZE';
export const PRODUCT_REQUEST_START = 'PRODUCT_REQUEST_START';
export const PRODUCT_REQUEST_FINISHED = 'PRODUCT_REQUEST_FINISHED';
export const PRODUCT_REQUEST_ERROR = 'PRODUCT_REQUEST_ERROR';
